
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Tiempos;

import Analizadores.Objetos.Atributo;
import Analizadores.Objetos.Token;
import Objetos.Tiempo;
import Objetos.Imagen;
import Objetos.Lienzo;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserTiempos extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserTiempos() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserTiempos(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserTiempos(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\034\000\002\002\004\000\002\002\011\000\002\002" +
    "\007\000\002\002\006\000\002\003\005\000\002\003\003" +
    "\000\002\004\007\000\002\004\006\000\002\004\005\000" +
    "\002\005\005\000\002\005\003\000\002\007\007\000\002" +
    "\007\007\000\002\007\007\000\002\007\005\000\002\007" +
    "\006\000\002\007\005\000\002\012\005\000\002\012\003" +
    "\000\002\011\005\000\002\011\005\000\002\006\005\000" +
    "\002\006\003\000\002\010\007\000\002\010\005\000\002" +
    "\010\005\000\002\010\005\000\002\010\006" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\125\000\006\003\004\015\006\001\002\000\010\003" +
    "\013\013\012\015\122\001\002\000\004\002\120\001\002" +
    "\000\004\011\007\001\002\000\004\021\010\001\002\000" +
    "\004\015\011\001\002\000\006\003\013\013\012\001\002" +
    "\000\004\021\114\001\002\000\014\003\023\004\025\005" +
    "\024\006\022\015\027\001\002\000\006\014\ufffc\016\ufffc" +
    "\001\002\000\006\014\016\016\017\001\002\000\006\003" +
    "\013\013\012\001\002\000\004\016\020\001\002\000\004" +
    "\002\000\001\002\000\006\014\ufffd\016\ufffd\001\002\000" +
    "\004\021\110\001\002\000\012\003\047\014\046\015\053" +
    "\017\051\001\002\000\004\021\042\001\002\000\004\021" +
    "\036\001\002\000\006\014\ufff7\016\ufff7\001\002\000\012" +
    "\003\023\004\025\005\024\006\022\001\002\000\006\014" +
    "\031\016\032\001\002\000\012\003\023\004\025\005\024" +
    "\006\022\001\002\000\006\014\ufff9\016\ufff9\001\002\000" +
    "\006\014\ufff8\016\ufff8\001\002\000\006\014\031\016\035" +
    "\001\002\000\006\014\ufffa\016\ufffa\001\002\000\004\022" +
    "\037\001\002\000\004\013\040\001\002\000\004\022\041" +
    "\001\002\000\006\014\ufff6\016\ufff6\001\002\000\004\022" +
    "\043\001\002\000\004\013\044\001\002\000\004\022\045" +
    "\001\002\000\006\014\ufff5\016\ufff5\001\002\000\012\003" +
    "\023\004\025\005\024\006\022\001\002\000\010\003\055" +
    "\007\057\010\056\001\002\000\010\014\uffef\016\uffef\020" +
    "\uffef\001\002\000\006\003\047\015\053\001\002\000\006" +
    "\014\076\020\102\001\002\000\010\003\055\007\057\010" +
    "\056\001\002\000\006\014\uffeb\016\uffeb\001\002\000\006" +
    "\014\072\016\073\001\002\000\004\021\070\001\002\000" +
    "\004\021\064\001\002\000\006\014\061\016\062\001\002" +
    "\000\010\003\055\007\057\010\056\001\002\000\010\014" +
    "\uffee\016\uffee\020\uffee\001\002\000\006\014\uffec\016\uffec" +
    "\001\002\000\004\022\065\001\002\000\004\013\066\001" +
    "\002\000\004\022\067\001\002\000\006\014\uffea\016\uffea" +
    "\001\002\000\004\012\071\001\002\000\006\014\uffe9\016" +
    "\uffe9\001\002\000\010\003\055\007\057\010\056\001\002" +
    "\000\010\003\047\015\053\016\074\001\002\000\012\003" +
    "\023\004\025\005\024\006\022\001\002\000\006\014\076" +
    "\016\uffe7\001\002\000\006\003\047\015\053\001\002\000" +
    "\010\014\ufff0\016\ufff0\020\ufff0\001\002\000\006\014\031" +
    "\016\uffe6\001\002\000\006\014\uffe8\016\uffe8\001\002\000" +
    "\006\014\ufff1\016\ufff1\001\002\000\006\014\076\020\104" +
    "\001\002\000\006\014\ufff2\016\ufff2\001\002\000\006\014" +
    "\061\016\106\001\002\000\010\014\uffed\016\uffed\020\uffed" +
    "\001\002\000\006\014\ufff3\016\ufff3\001\002\000\004\017" +
    "\111\001\002\000\006\003\047\015\053\001\002\000\006" +
    "\014\076\020\113\001\002\000\006\014\ufff4\016\ufff4\001" +
    "\002\000\004\015\115\001\002\000\012\003\023\004\025" +
    "\005\024\006\022\001\002\000\006\014\031\016\117\001" +
    "\002\000\006\014\ufffb\016\ufffb\001\002\000\004\002\001" +
    "\001\002\000\006\014\016\016\126\001\002\000\006\003" +
    "\013\013\012\001\002\000\006\014\016\016\124\001\002" +
    "\000\004\016\125\001\002\000\004\002\uffff\001\002\000" +
    "\004\016\127\001\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\125\000\004\002\004\001\001\000\006\003\120\004" +
    "\013\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\003\014\004\013\001" +
    "\001\000\002\001\001\000\006\005\027\007\025\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\004\020\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\011\047\012\051\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\005\033\007\025\001\001\000\002\001\001\000\004\007" +
    "\032\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\005\106\007\025\001\001\000\006\006\104\010\053" +
    "\001\001\000\002\001\001\000\006\011\047\012\102\001" +
    "\001\000\002\001\001\000\006\006\057\010\053\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\010\062\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\006\100\010\053\001" +
    "\001\000\006\011\047\012\074\001\001\000\006\005\077" +
    "\007\025\001\001\000\002\001\001\000\004\011\076\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\011\047\012\111\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\005\115" +
    "\007\025\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\003\122\004\013" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserTiempos$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserTiempos$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserTiempos$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        
        private List<String> listErrores = new ArrayList<String>();
        private List<Lienzo> listLienzos = new ArrayList<Lienzo>();

        public List<String> getErrores(){
            return listErrores;
        }
        
        public List<Lienzo> getLienzos(){
            return listLienzos;
        }

        public ParserTiempos(LexerTiempos lex, List<Lienzo> lienzos) { 
            super(lex);   
            listLienzos = lienzos;
            listErrores = lex.getErrorsList();
	}

        public void unrecovered_syntax_error(Symbol cur_token){
            System.err.println("Couldn't repair and continue parse "+((Token)cur_token.value).getLexema());
        }

        public void syntax_error(Symbol s){
            String message = "";
            StringBuilder m = new StringBuilder("Error:");
            String cadena = ((Token)s.value).getLexema();
            int linea = (((Token)s.value).getLinea());
            int columna = (((Token)s.value).getColumna());
            switch(s.toString()){
                case "#2": case "#3": case "#4": case "#5": case "#6": case "#7": {
                    message = "No se esperaba una palabra reservada, probablemente hace falta un fin de linea anteriormente";
                    break;
                }
                case "#8": message = "No se esperaba un entero, verifique que el tipo de dato del atributo que desea asignar, sea un entero"; break;
                case "#9": message = "No se esperaba un id, verifique se se haya finalizado correctamente la linea anterior"; break;
                case "#10": message = "No se esperaba una coma, verifique que efectivamente se trate de un fin de linea"; break;
                case "#11": message = "No se esperaba una llave abierta"; break;
                case "#12": message = "No se esperaba una llave cerrada"; break;
                case "#13": message = "No se esperaba un corchete abierto"; break;
                case "#14": message = "No se esperaba un corchete cerrado"; break;
                case "#15": message = "No se esperaba una asignacion, verifique que antes se encuentre un id o una palabra reservada"; break;
                case "#16": message = "No se esperaba una comilla, verifique que el tipo de dato del atributo que desea asignar, sea una cadena"; break;
            }
            listErrores.add("Se ha encontrado un error en la linea: "+linea+", columna: "+columna+" con la cadena "+cadena+"|Descripcion: "+message);
        }
        


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserTiempos$actions {



    private boolean isValido(Imagen imagen){
        boolean valor = true;
        if(imagen.getId()==null) {
            listErrores.add("Hay un error con la imagen declarada en la linea: "+imagen.getLineaT()+", columna: "+imagen.getColumnaT()+" no posee un id");
            valor = false;
        }
        if(imagen.getDuracion()==(-1)){
            listErrores.add("Hay un error con la imagen declarada en la linea: "+imagen.getLineaT()+", columna: "+imagen.getColumnaT()+" no posee una duracion");
            valor = false;
        }
        return valor;
    }

    private void imagenesRepetidas(List<Imagen> imagenes){
        List<String> ids = new ArrayList<String>();
        for(Imagen imagen : imagenes){
            boolean existe = false;
            for(String id : ids){
                if(id.equals(imagen.getId())) existe = true;
            }
            ids.add(imagen.getId());
            if(existe) listErrores.add("Ya existe una imagen declarada con el id "+imagen.getId()+", error en la linea "+imagen.getLineaT()+", columna: "+imagen.getColumnaT());
        }
    }

    private boolean isValido(Tiempo tiempo){
        boolean valor = true;
        if(tiempo.getIdInicio()!= null && tiempo.getIdFin()!=null){
            if(tiempo.existe(tiempo.getIdInicio()) && tiempo.existe(tiempo.getIdFin())){
                if(tiempo.getIndice(tiempo.getIdInicio()) >= tiempo.getIndice(tiempo.getIdFin())){
                    listErrores.add("El idInicio se encuentra después que el idFin, en el tiempo del lienzo declarado en la linea : "+tiempo.getLineaT()+", columna: "+tiempo.getColumnaT());
                    valor = false;
                }
            }else{
                if(!tiempo.existe(tiempo.getIdInicio())){
                    listErrores.add("No existe el idInicio, en la lista de imagenes, en el tiempo del lienzo declarado en la linea: "+tiempo.getLineaT()+", columna: "+tiempo.getColumnaT());
                    valor = false;
                }
                if(!tiempo.existe(tiempo.getIdFin())) {
                    listErrores.add("No existe el idFin, en la lista de imagenes, en el tiempo del lienzo declarado en la linea : "+tiempo.getLineaT()+", columna: "+tiempo.getColumnaT());
                    valor= false;
                }
            }
        }else{
            if(tiempo.getIdInicio() == null){
                listErrores.add("Hay un error con el tiempo del lienzo declarado en la linea: "+tiempo.getLineaT()+", columna: "+tiempo.getColumnaT()+" no posee un idInicio");
                valor = false;
            }else{
                if(!tiempo.existe(tiempo.getIdInicio())){
                    listErrores.add("No existe el idInicio, en la lista de imagenes, en el tiempo del lienzo declarado en la linea: "+tiempo.getLineaT()+", columna: "+tiempo.getColumnaT());
                    valor = false;
                }
            }
            if(tiempo.getIdFin() == null){
                valor = false;
                listErrores.add("Hay un error con el tiempo del lienzo declarado en la linea: "+tiempo.getLineaT()+", columna: "+tiempo.getColumnaT()+" no posee un idFIn");
            }else{
                if(!tiempo.existe(tiempo.getIdFin())) {
                    listErrores.add("No existe el idFin, en la lista de imagenes, en el tiempo del lienzo declarado en la linea : "+tiempo.getLineaT()+", columna: "+tiempo.getColumnaT());
                    valor = false;
                }
            }
        }
        return valor;
    }

    private void inicializarTiempo(Tiempo tiempo, List<Atributo> atributos){
        for(Atributo atributo : atributos){
            switch(atributo.getTipo()){
                case "inicio":{
                    if(tiempo.getIdInicio() != null){
                        listErrores.add("Ya existe un valor asignado, atributo inicio repetido en la linea: "+atributo.getLinea()+", columna: "+atributo.getColumna());
                    }else{
                        tiempo.setIdInicio((String)atributo.getValor());
                    }
                    break;
                }
                case "fin":{
                    if(tiempo.getIdFin() != null){
                        listErrores.add("Ya existe un valor asignado, atributo fin repetido en la linea: "+atributo.getLinea()+", columna: "+atributo.getColumna());
                    }else{
                        tiempo.setIdFin((String)atributo.getValor());
                    }
                    break;
                }
                case "imagenes":{
                    if(!tiempo.getImagenes().isEmpty()){
                        listErrores.add("Ya existe un valor asignado, atributo imagenes repetido en la linea: "+atributo.getLinea()+", columna: "+atributo.getColumna());
                    }else{
                        tiempo.setImagenes((List<Imagen>)atributo.getValor());
                    }
                    break;
                }
            }
        }
    }

    private void inicializarImagen(Imagen imagen, List<Atributo> atributos){
        for(Atributo atributo : atributos){
            switch(atributo.getTipo()){
                case "id":{
                    if(imagen.getId() != null){
                        listErrores.add("Ya existe un valor asignado, atributo id repetido en la linea: "+atributo.getLinea()+", columna: "+atributo.getColumna());
                    }else{
                        imagen.setId((String) atributo.getValor());
                    }
                    break;
                }
                case "duracion":{
                    if(imagen.getDuracion() != (-1)){
                        listErrores.add("Ya existe un valor asignado, atributo duracion repetido en la linea: "+atributo.getLinea()+", columna: "+atributo.getColumna());
                    }else{
                        imagen.setDuracion(Integer.parseInt((String)atributo.getValor()));
                    }
                    break;
                }
            }
        }
    }

    private Lienzo getLienzoPorId(String id){
        Lienzo lienzo = null;
        for(Lienzo temp : listLienzos){
            if(temp.getId().equals(id)) lienzo = temp;
        }
        return lienzo;
    }


  private final ParserTiempos parser;

  /** Constructor */
  CUP$ParserTiempos$actions(ParserTiempos parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserTiempos$do_action_part00000000(
    int                        CUP$ParserTiempos$act_num,
    java_cup.runtime.lr_parser CUP$ParserTiempos$parser,
    java.util.Stack            CUP$ParserTiempos$stack,
    int                        CUP$ParserTiempos$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserTiempos$result;

      /* select the action based on the action number */
      switch (CUP$ParserTiempos$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).value;
		RESULT = start_val;
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserTiempos$parser.done_parsing();
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= LLAVE_A PR_TIEMPOS ASIGNACION LLAVE_A strTiempos LLAVE_C LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-6)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // S ::= error LLAVE_A strTiempos LLAVE_C LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // S ::= error strTiempos LLAVE_C LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-3)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // strTiempos ::= strTiempos COMA inicioTiemposLienzo 
            {
              Object RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("strTiempos",1, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // strTiempos ::= inicioTiemposLienzo 
            {
              Object RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("strTiempos",1, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // inicioTiemposLienzo ::= ID ASIGNACION LLAVE_A strTiempo LLAVE_C 
            {
              Object RESULT =null;
		int lienzoleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).left;
		int lienzoright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).right;
		Token lienzo = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).value;
		int listAtributosleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).left;
		int listAtributosright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).right;
		List<Atributo> listAtributos = (List<Atributo>)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).value;
		
                                            Tiempo tiempo = new Tiempo();
                                            if(listAtributos != null){
                                                inicializarTiempo(tiempo, listAtributos);
                                                tiempo.setLineaT(lienzo.getLinea());
                                                tiempo.setColumnaT(lienzo.getColumna());
                                                if(lienzo != null){
                                                    if(getLienzoPorId(lienzo.getLexema()) != null){
                                                        if(getLienzoPorId(lienzo.getLexema()).getTiempos() != null){
                                                            listErrores.add("Ya se declaró la estructura tiempos que tendra el lienzo "+lienzo.getLexema()+" en la linea: "+lienzo.getLinea()+", columna: "+lienzo.getColumna());
                                                        }else{
                                                            if(isValido(tiempo)) getLienzoPorId(lienzo.getLexema()).setTiempos(tiempo);
                                                        }
                                                    }else{
                                                        listErrores.add("No existe el lienzo escrito, en la linea: "+lienzo.getLinea()+", columna: "+lienzo.getColumna());
                                                    }
                                                }
                                            }
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("inicioTiemposLienzo",2, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // inicioTiemposLienzo ::= error LLAVE_A strTiempo LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("inicioTiemposLienzo",2, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-3)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // inicioTiemposLienzo ::= error strTiempo LLAVE_C 
            {
              Object RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("inicioTiemposLienzo",2, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // strTiempo ::= strTiempo COMA paramTiempo 
            {
              List<Atributo> RESULT =null;
		int listAtributosleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).left;
		int listAtributosright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).right;
		List<Atributo> listAtributos = (List<Atributo>)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).value;
		int atributoleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).left;
		int atributoright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).right;
		Atributo atributo = (Atributo)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.peek()).value;
		
                                            if(listAtributos == null) listAtributos = new ArrayList<Atributo>();
                                            if(atributo != null) listAtributos.add(atributo);
                                            RESULT = listAtributos;
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("strTiempo",3, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // strTiempo ::= paramTiempo 
            {
              List<Atributo> RESULT =null;
		int atributoleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).left;
		int atributoright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).right;
		Atributo atributo = (Atributo)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.peek()).value;
		
                                            ArrayList<Atributo> atributos = new ArrayList<Atributo>();
                                            if(atributo != null) atributos.add(atributo);
                                            RESULT = atributos;
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("strTiempo",3, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // paramTiempo ::= PR_INICIO ASIGNACION COMILLA ID COMILLA 
            {
              Atributo RESULT =null;
		int dclleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).left;
		int dclright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).right;
		Token dcl = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).value;
		
                                            if(id != null){
                                                if(dcl != null){
                                                    Atributo atributo = new Atributo("inicio", id.getLexema(), dcl.getLinea(), dcl.getColumna());
                                                    RESULT = atributo;
                                                }
                                            }    
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramTiempo",5, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // paramTiempo ::= PR_FIN ASIGNACION COMILLA ID COMILLA 
            {
              Atributo RESULT =null;
		int dclleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).left;
		int dclright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).right;
		Token dcl = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).value;
		
                                            if(id != null){
                                                if(dcl != null){
                                                    Atributo atributo = new Atributo("fin", id.getLexema(), dcl.getLinea(), dcl.getColumna());
                                                    RESULT = atributo;
                                                }
                                            }    
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramTiempo",5, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // paramTiempo ::= PR_IMAGENES ASIGNACION CORCHETE_A listImagenes CORCHETE_C 
            {
              Atributo RESULT =null;
		int dclleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).left;
		int dclright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).right;
		Token dcl = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).value;
		int imagenesleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).left;
		int imagenesright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).right;
		List<Imagen> imagenes = (List<Imagen>)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).value;
		
                                            if(imagenes != null){
                                                if(dcl != null){
                                                    imagenesRepetidas(imagenes);
                                                    Atributo atributo = new Atributo("imagenes", imagenes, dcl.getLinea(), dcl.getColumna());
                                                    RESULT = atributo;
                                                }
                                            }    
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramTiempo",5, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // paramTiempo ::= error COMA strTiempo 
            {
              Atributo RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramTiempo",5, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // paramTiempo ::= error CORCHETE_A listImagenes CORCHETE_C 
            {
              Atributo RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramTiempo",5, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-3)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // paramTiempo ::= error listImagenes CORCHETE_C 
            {
              Atributo RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramTiempo",5, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // listImagenes ::= listImagenes COMA strImagen 
            {
              List<Imagen> RESULT =null;
		int imagenesleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).left;
		int imagenesright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).right;
		List<Imagen> imagenes = (List<Imagen>)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).value;
		int imagenleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).left;
		int imagenright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).right;
		Imagen imagen = (Imagen)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.peek()).value;
		
                                            if(imagenes == null) imagenes = new ArrayList<Imagen>();
                                            if(imagen != null){
                                                if(isValido(imagen)) imagenes.add(imagen);
                                            }
                                            RESULT = imagenes;
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("listImagenes",8, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // listImagenes ::= strImagen 
            {
              List<Imagen> RESULT =null;
		int imagenleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).left;
		int imagenright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).right;
		Imagen imagen = (Imagen)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.peek()).value;
		
                                            ArrayList<Imagen> imagenes = new ArrayList<Imagen>();
                                            if(imagen != null){
                                                if(isValido(imagen)) imagenes.add(imagen);
                                            }
                                            RESULT = imagenes;
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("listImagenes",8, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // strImagen ::= LLAVE_A paramsImagen LLAVE_C 
            {
              Imagen RESULT =null;
		int dclleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).left;
		int dclright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).right;
		Token dcl = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).value;
		int listAtributosleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).left;
		int listAtributosright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).right;
		List<Atributo> listAtributos = (List<Atributo>)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).value;
		
                                            if(listAtributos != null){
                                                Imagen imagen = new Imagen();
                                                if(dcl!=null) imagen.setLineaT(dcl.getLinea());
                                                if(dcl!=null) imagen.setColumnaT(dcl.getColumna());
                                                inicializarImagen(imagen, listAtributos);
                                                RESULT = imagen;
                                            }
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("strImagen",7, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // strImagen ::= error paramsImagen LLAVE_C 
            {
              Imagen RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("strImagen",7, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // paramsImagen ::= paramsImagen COMA paramImagen 
            {
              List<Atributo> RESULT =null;
		int listAtributosleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).left;
		int listAtributosright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).right;
		List<Atributo> listAtributos = (List<Atributo>)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).value;
		int atributoleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).left;
		int atributoright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).right;
		Atributo atributo = (Atributo)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.peek()).value;
		
                                            if(listAtributos == null) listAtributos = new ArrayList<Atributo>();
                                            if(atributo != null) listAtributos.add(atributo);
                                            RESULT = listAtributos;
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramsImagen",4, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // paramsImagen ::= paramImagen 
            {
              List<Atributo> RESULT =null;
		int atributoleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).left;
		int atributoright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).right;
		Atributo atributo = (Atributo)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.peek()).value;
		
                                            ArrayList<Atributo> listAtributos = new ArrayList<Atributo>();
                                            if(atributo != null) listAtributos.add(atributo);
                                            RESULT = listAtributos;
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramsImagen",4, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // paramImagen ::= PR_ID ASIGNACION COMILLA ID COMILLA 
            {
              Atributo RESULT =null;
		int dclleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).left;
		int dclright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).right;
		Token dcl = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-1)).value;
		
                                            if(id != null){
                                                if(dcl != null){
                                                    Atributo atributo = new Atributo("id", id.getLexema(), dcl.getLinea(), dcl.getColumna());
                                                    RESULT = atributo;
                                                }
                                            }
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramImagen",6, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-4)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // paramImagen ::= PR_DURACION ASIGNACION ENTERO 
            {
              Atributo RESULT =null;
		int dclleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).left;
		int dclright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).right;
		Token dcl = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$ParserTiempos$stack.peek()).value;
		
                                            if(id != null){
                                                if(dcl != null){
                                                    Atributo atributo = new Atributo("duracion", id.getLexema(), dcl.getLinea(), dcl.getColumna());
                                                    RESULT = atributo;
                                                }
                                            }
                                        
              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramImagen",6, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // paramImagen ::= error COMA paramsImagen 
            {
              Atributo RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramImagen",6, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // paramImagen ::= error LLAVE_C listImagenes 
            {
              Atributo RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramImagen",6, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-2)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // paramImagen ::= error LLAVE_C LLAVE_C strTiempo 
            {
              Atributo RESULT =null;

              CUP$ParserTiempos$result = parser.getSymbolFactory().newSymbol("paramImagen",6, ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.elementAt(CUP$ParserTiempos$top-3)), ((java_cup.runtime.Symbol)CUP$ParserTiempos$stack.peek()), RESULT);
            }
          return CUP$ParserTiempos$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserTiempos$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserTiempos$do_action(
    int                        CUP$ParserTiempos$act_num,
    java_cup.runtime.lr_parser CUP$ParserTiempos$parser,
    java.util.Stack            CUP$ParserTiempos$stack,
    int                        CUP$ParserTiempos$top)
    throws java.lang.Exception
    {
              return CUP$ParserTiempos$do_action_part00000000(
                               CUP$ParserTiempos$act_num,
                               CUP$ParserTiempos$parser,
                               CUP$ParserTiempos$stack,
                               CUP$ParserTiempos$top);
    }
}

}
