
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Json;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 4;
  public static final int ID = 3;
  public static final int ASIGNACION = 7;
  public static final int error = 1;
  public static final int VALOR = 2;
  public static final int LLAVE_C = 6;
  public static final int EOF = 0;
  public static final int LLAVE_A = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VALOR",
  "ID",
  "COMA",
  "LLAVE_A",
  "LLAVE_C",
  "ASIGNACION"
  };
}

