
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.Lienzos;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PR_LIENZOS = 2;
  public static final int LLAVE_A = 3;
  public static final int LLAVE_C = 4;
  public static final int ASIGNACION = 5;
  public static final int PR_NOMBRE = 6;
  public static final int PR_TIPO = 7;
  public static final int COMA = 8;
  public static final int PR_FONDO = 9;
  public static final int PR_TAMANO = 10;
  public static final int PR_CUADRO = 11;
  public static final int PR_DX = 12;
  public static final int PR_DY = 13;
  public static final int PR_RED = 14;
  public static final int PR_GREEN = 15;
  public static final int PR_BLUE = 16;
  public static final int PR_HEX = 17;
  public static final int COMILLA = 18;
  public static final int ID = 19;
  public static final int HEX = 20;
  public static final int EXTENSION = 21;
  public static final int ENTERO = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_LIENZOS",
  "LLAVE_A",
  "LLAVE_C",
  "ASIGNACION",
  "PR_NOMBRE",
  "PR_TIPO",
  "COMA",
  "PR_FONDO",
  "PR_TAMANO",
  "PR_CUADRO",
  "PR_DX",
  "PR_DY",
  "PR_RED",
  "PR_GREEN",
  "PR_BLUE",
  "PR_HEX",
  "COMILLA",
  "ID",
  "HEX",
  "EXTENSION",
  "ENTERO"
  };
}

